version: '3'
services:
  api-gateway-1:
    build: ../api-gateway-1/
    image: "api-gateway-1"
    container_name: "api-gateway-1"
    ports:
      - "8443:8443"
    networks:
      - s3v7-network
    depends_on:
      - users-service
      - videos-service
      - wta-service

  api-gateway-2:
    build: ../api-gateway-2/
    image: "api-gateway-2"
    container_name: "api-gateway-2"
    ports:
      - "8080:8080"
    networks:
      - s3v7-network
    depends_on:
      - managers-service
      - wta-service

  users-service:
    build: ../users-service/
    image: "users-service"
    container_name: "users-service"
    networks:
      - s3v7-network
    depends_on:
      - users-mariadb

  users-mariadb:
    image: "mariadb"
    container_name: "users-mariadb"
    networks:
      - s3v7-network
    volumes:
      - usersmariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD:root-password
     
  managers-service:
    build: ../managers-service/
    image: "managers-service"
    container_name: "managers-service"
    networks:
      - s3v7-network
    depends_on:
      - managers-mariadb

  managers-mariadb:
    image: "mariadb"
    container_name: "managers-mariadb"
    networks:
      - s3v7-network
    volumes:
      - mariadb-managers:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD:root-password

  sessions-service:
    build: ../sessions-service/
    image: "sessions-service"
    container_name: "sessions-service"
    networks:
      - s3v7-network
    depends_on:
      - sessions-redis

  sessions-redis:
    image: "redis"
    container_name: "sessions-redis"
    networks:
      - s3v7-network

  videos-service:
    build: ../videos-service/
    image: "videos-service"
    container_name: "videos-service"
    networks:
      - s3v7-network
    depends_on:
      - videos-mariadb

  videos-mariadb:
    image: "mariadb"
    container_name: "videos-mariadb"
    networks:
      - s3v7-network
    volumes:
      - mariadb-videos:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD:root-password

  wta-service:
    build: ../wta-service/
    image: "wta-service"
    container_name: "wta-service"
    networks:
      - s3v7-network
    depends_on:
      - wta-psql

  wta-psql:
    image: "postgres"
    container_name: "wta-psql"
    networks:
      - s3v7-network
    volumes:
      - postgres-wta:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD:packt
      - POSTGRES_USER:packt
      - POSTGRES_DB=wta

networks:
  s3v7-network:

volumes:
  usersmariadb:
    external: true
  mariadb-managers:
    external: true
  mariadb-videos:
    external: true
  postgres-wta:
    external: true
